language: java

branches:
  except:
  - gh-pages
  - /^tag.*$/

env:
  global:
  - secure: c6MyQOm1B//KGDpJ+swHWgWJSp/XEkkZ61ZMeF02VxdMM2kJmGAaMfCjIrF3+0wSOKs4V/3LzjHefY4OMTBMuf/snrlXfWRRIymNIvsgEvFPKQHz/YunFdoHmhF54fgRQt+lmeKwKL/p/4PG2hdzo3e0+sufbXAAphQ01Vo8wg0=
  - secure: jP+6no77LmkNsx9/ih/q4fECS+6g2HxXcmLk3kEw309BTfmi270578YTFrhquwnXO4iRWG02Uza3Qs7lwLLlUIz+KRhBgDG1kcLa/juJEqxBfJ9nsbxbBU6ncnSHvOGWh3dYXWGjXzWKACSb0tGF+BL4RG8aq4/9k60++/11zM8=
  - secure: p4TxOFCOSPKKb6g3ZlDeJFuUQ35wKKT+5Ae5ugDORnh09RXzwLRSglItEY29s2mK/lnAyn77U3HZQiXPGkLiZK5w8Vzb6KFr8NYbMvwz53MIMyZlKEg6nJEddk998vwNdB06tJ0qjmZYK1aGJx53oPm90drF00uLmOk65WRk2P0=
  - secure: Hx9bFf/LqxbMEyBPZTLVKIiTjNw0NFC7zXx7Ht/kcAVxlgyhid7k2Nx1p0JZwlsACXSzoWBlizxhrOQZz0J1GqOP68mOOeJxWyk4vQH9EvaX0bYjKYnlygqfEhGMjYs1pMnwg5jETRc0yHbJCwQKMTLpH/ja1mGINNMTCl9+Nes=
  - secure: H4CKwlSHG6vGlDGJINH//dfFim8v4IaljlIlMSGsjn+hiIAA8vvJ1s6RTJdev30twbmgYNK/sQcBiQ51oFNqtOpoIfQfyPRxd3yZrFVJ3XQg8W/Dc9k/EOWAl2+9k1XSaDkI8I+Lmgqeac+xL/91TcaHkQv45/24VxLaE/WRECY=

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      jdk: oraclejdk7
    - os: linux
      dist: trusty
      jdk: oraclejdk8
      script:
        - mvn install -B -V 
        # SonarQube needs to be run with at least Java 8
        # Make sure we are on dev for running SonarQube
        - if [[ $TRAVIS_BRANCH == dev ]]; then mvn sonar:sonar -Dsonar.host.url=https://sonarqube.com -Dsonar.login=$SONARQUBE_TOKEN; fi
      after_success:
      - true

install:
- true

script:
- mvn install -B -V

after_success:
- mvn com.gavinmogan:codacy-maven-plugin:coverage -DcoverageReportFile=target/site/jacoco/jacoco.xml -DprojectToken=$CODACY_PROJECT_TOKEN -DapiToken=$CODACY_API_TOKEN
