language: java
jdk:
- oraclejdk8
- oraclejdk7
- openjdk7
os:
- linux
branches:
  only:
  - master
  - dev
  - coverity_scan
before_script:
  - pip install --user codecov
after_success:
- codecov
env:
  global:
    secure: JBPvTE+7g7FhS1HdvLyNx1eBJBTE9DHmqU3kQNKz87lBp83etXMl/tNWH8P2LAKGIewmu/Oh7WpS1nr4CtnU1DhNIlPIaSaMTwkowodGwTOlAA+Iat6yRbxnS+5b+ev+PjtcJ/JF20buwUPiMNDWIU+qKIHaqnYhW6kdt6bedcQ=
addons:
  coverity_scan:
    project:
      name: dannil/scb-api
      description: Build submitted via Travis CI
    notification_email: daniel.nilsson94@outlook.com
    build_command_prepend: mvn clean
    build_command: mvn -DskipTests=true compile
    branch_pattern: coverity_scan