language: java
branches:
  except:
  - gh-pages
  - /^tag.*$/
env:
  global:
  - secure: c6MyQOm1B//KGDpJ+swHWgWJSp/XEkkZ61ZMeF02VxdMM2kJmGAaMfCjIrF3+0wSOKs4V/3LzjHefY4OMTBMuf/snrlXfWRRIymNIvsgEvFPKQHz/YunFdoHmhF54fgRQt+lmeKwKL/p/4PG2hdzo3e0+sufbXAAphQ01Vo8wg0=
  #- secure: jP+6no77LmkNsx9/ih/q4fECS+6g2HxXcmLk3kEw309BTfmi270578YTFrhquwnXO4iRWG02Uza3Qs7lwLLlUIz+KRhBgDG1kcLa/juJEqxBfJ9nsbxbBU6ncnSHvOGWh3dYXWGjXzWKACSb0tGF+BL4RG8aq4/9k60++/11zM8=
  #- secure: p4TxOFCOSPKKb6g3ZlDeJFuUQ35wKKT+5Ae5ugDORnh09RXzwLRSglItEY29s2mK/lnAyn77U3HZQiXPGkLiZK5w8Vzb6KFr8NYbMvwz53MIMyZlKEg6nJEddk998vwNdB06tJ0qjmZYK1aGJx53oPm90drF00uLmOk65WRk2P0=
matrix:
  include:
  - os: linux
    dist: trusty
    sudo: required
    jdk: oraclejdk8
before_script:
# If we get the same IP on concurrent builds and this triggers an error
# on the API (rate limiting), this can be easily debugged by checking the log
# where this command printed its result
- curl icanhazip.com
install:
- true
script:
- mvn install -B -V -DtestsDayLimit=7
- if [[ $TRAVIS_BRANCH == test/run-all-tests ]]; then mvn sonar:sonar -Dsonar.host.url=https://sonarqube.com -Dsonar.login=$SONARQUBE_TOKEN; fi
