# build version
version: '{build}'

branches:
  except:
  - gh-pages


environment:
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.7.0
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0

install:
- true

build_script:
- mvn install -Dmaven.javadoc.skip=true -B -V
